#!/bin/bash
# ============================================================
# Mac Mini Chrome セットアップスクリプト（日向エージェント用）
#
# 実行タイミング:
#   - Mac Mini 再起動後の初回ログイン時
#   - Chrome の環境を再構築する必要があるとき
#
# 使い方:
#   bash ~/agents/System/hinata/setup_chrome.sh
# ============================================================

set -e

CHROME_PROFILE="$HOME/agents/System/data/hinata_chrome_profile"
PLIST_SRC="$HOME/agents/System/hinata/com.hinata.chrome.plist"
PLIST_DST="$HOME/Library/LaunchAgents/com.hinata.chrome.plist"
EXTENSION_ID="fcoeoabgfenejglbffodgkkbkcdhcgfn"  # Claude in Chrome
EXT_PREFS_DIR="$CHROME_PROFILE/Default/External Extensions"
NATIVE_HOST_MANIFEST="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.anthropic.claude_code_browser_extension.json"
NATIVE_HOST_SCRIPT="$HOME/.claude/chrome/chrome-native-host"

echo "=== 日向 Chrome セットアップ ==="

# ---- 0. Claude Code Native Messaging Host の確認 ----
echo "[0/7] Claude Code Native Messaging Host 確認..."
CLAUDE_BIN=$(which claude 2>/dev/null || echo "/opt/homebrew/bin/claude")
CLAUDE_VERSION=$("$CLAUDE_BIN" --version 2>/dev/null | head -1 || echo "不明")
echo "  → Claude Code: $CLAUDE_VERSION ($CLAUDE_BIN)"

# chrome-native-host が正しい Claude Code バージョンを指しているか確認
if [ -f "$NATIVE_HOST_SCRIPT" ]; then
    CURRENT_HOST=$(cat "$NATIVE_HOST_SCRIPT")
    echo "  → Native Host: $(echo "$CURRENT_HOST" | grep exec)"
    # バージョンパスが存在するか確認
    HOST_PATH=$(echo "$CURRENT_HOST" | grep exec | sed 's/exec "//' | sed 's/" .*//')
    if [ ! -f "$HOST_PATH" ]; then
        echo "  ⚠️ Native Host のバイナリが見つかりません: $HOST_PATH"
        echo "  → 現在の Claude Code で再生成します"
        REAL_CLAUDE=$(readlink -f "$CLAUDE_BIN" 2>/dev/null || "$CLAUDE_BIN" --version 2>/dev/null | head -1)
        # Claude Code のバイナリパスを取得
        CLAUDE_REAL_PATH=$(ls -la "$HOME/.local/share/claude/versions/" 2>/dev/null | tail -1 | awk '{print $NF}')
        if [ -n "$CLAUDE_REAL_PATH" ] && [ -f "$HOME/.local/share/claude/versions/$CLAUDE_REAL_PATH" ]; then
            mkdir -p "$(dirname "$NATIVE_HOST_SCRIPT")"
            cat > "$NATIVE_HOST_SCRIPT" << HOSTEOF
#!/bin/sh
# Chrome native host wrapper script
# Generated by setup_chrome.sh
exec "$HOME/.local/share/claude/versions/$CLAUDE_REAL_PATH" --chrome-native-host
HOSTEOF
            chmod +x "$NATIVE_HOST_SCRIPT"
            echo "  → Native Host を更新しました"
        fi
    else
        echo "  → Native Host OK"
    fi
else
    echo "  ⚠️ Native Host スクリプトが存在しません"
    echo "  → Claude Code を一度インタラクティブに起動してセットアップしてください"
fi

# Native Messaging Host マニフェストの確認
if [ -f "$NATIVE_HOST_MANIFEST" ]; then
    echo "  → NativeMessagingHosts マニフェスト OK"
else
    echo "  ⚠️ NativeMessagingHosts マニフェストがありません"
    echo "  → Claude Code を一度起動して chrome 連携を設定してください"
fi

# ---- 1. Chrome plist のインストール ----
echo "[1/7] Chrome plist を更新..."
launchctl unload "$PLIST_DST" 2>/dev/null || true
cp "$PLIST_SRC" "$PLIST_DST"
echo "  → $PLIST_DST にコピー完了"

# ---- 2. Chrome プロファイルディレクトリの準備 ----
echo "[2/7] Chrome プロファイル確認..."
mkdir -p "$CHROME_PROFILE/Default"
echo "  → $CHROME_PROFILE"

# ---- 3. Claude in Chrome 拡張機能の外部インストール設定 ----
echo "[3/7] Claude in Chrome 拡張機能の自動インストール設定..."
mkdir -p "$EXT_PREFS_DIR"
cat > "$EXT_PREFS_DIR/$EXTENSION_ID.json" << 'EXTJSON'
{
    "external_update_url": "https://clients2.google.com/service/update2/crx"
}
EXTJSON
echo "  → External Extensions に $EXTENSION_ID を登録"

# システム全体にも設定（念のため）
sudo mkdir -p "/Library/Google/Chrome/External Extensions" 2>/dev/null || true
if [ -w "/Library/Google/Chrome/External Extensions" ] 2>/dev/null; then
    cat > "/Library/Google/Chrome/External Extensions/$EXTENSION_ID.json" << 'EXTJSON'
{
    "external_update_url": "https://clients2.google.com/service/update2/crx"
}
EXTJSON
    echo "  → /Library/Google/Chrome/External Extensions にも登録"
fi

# ---- 4. Chrome を起動 ----
echo "[4/7] Chrome を起動..."
killall "Google Chrome" 2>/dev/null || true
sleep 2
launchctl load "$PLIST_DST"
sleep 10

# 起動確認
CHROME_COUNT=$(ps aux | grep "[G]oogle Chrome" | grep -v zsh | wc -l | tr -d ' ')
if [ "$CHROME_COUNT" -gt 3 ]; then
    echo "  → Chrome 起動成功（$CHROME_COUNT プロセス）"
else
    echo "  ⚠️ Chrome の起動が不完全（$CHROME_COUNT プロセス）"
    echo "  → Dock から手動で Chrome を起動してください"
    echo "  → または: open -a 'Google Chrome' --args --user-data-dir=$CHROME_PROFILE --remote-debugging-port=9223"
fi

# ---- 5. ポート確認 ----
echo "[5/7] デバッグポート確認..."
if lsof -i :9223 -P >/dev/null 2>&1; then
    echo "  → ポート 9223 OK"
    CHROME_VERSION=$(curl -s http://localhost:9223/json/version 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('Browser','?'))" 2>/dev/null || echo "取得失敗")
    echo "  → Chrome: $CHROME_VERSION"
else
    echo "  ⚠️ ポート 9223 が応答しません"
fi

# ---- 6. サービス状態確認 ----
echo "[6/7] 全サービス状態..."
echo "  Orchestrator: $(launchctl list | grep addness | awk '{print $1=="0" || $1=="-" ? "OK" : "NG"}')"
echo "  日向エージェント: $(launchctl list | grep hinata.agent | awk '{print $1=="0" || $1=="-" ? "OK" : "NG"}')"
echo "  local_agent: $(launchctl list | grep linebot | awk '{print $1=="0" || $1=="-" ? "OK" : "NG"}')"
echo "  Chrome: $(launchctl list | grep hinata.chrome | awk '{print $1=="0" || $1=="-" ? "OK" : "NG"}')"

# ---- 7. 自動ログイン確認 ----
echo "[7/7] 自動ログイン設定確認..."
AUTO_LOGIN=$(sudo defaults read /Library/Preferences/com.apple.loginwindow autoLoginUser 2>/dev/null || echo "未設定")
if [ "$AUTO_LOGIN" != "未設定" ]; then
    echo "  → 自動ログイン: $AUTO_LOGIN"
else
    echo "  ⚠️ 自動ログインが未設定です"
    echo "  → 再起動時にログイン画面で止まる原因になります"
    echo "  → システム設定 > ユーザとグループ > ログインオプション で設定してください"
fi

echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "次のステップ:"
echo "  1. Chrome で https://www.addness.com を開いてログイン確認"
echo "     ログインメール: hinata@team.addness.co.jp"
echo "  2. Claude in Chrome 拡張機能が有効か確認"
echo "     chrome://extensions/ で確認"
echo "  3. 自動ログインを有効にする（次回再起動対策）:"
echo "     システム設定 > ユーザとグループ > ログインオプション > 自動ログイン"
