#!/usr/bin/env python3
"""
【アドネス株式会社】スキルプラス自動生成データ（加工）を再生成する。

方針:
- 正本は `【スキルプラス】イベント管理シート` の raw タブ群
- 取れる指標だけを正本化し、取れない指標は無理に埋めない
- visible タブは `自動生成一覧 / 自動生成サマリー / データソース管理 / データ追加ルール` の4つだけ
- `連続アクション日数 / 累計アクション日数 / ゴール達成数 / 最終アクション日` は将来接続用の列として持つが、現時点では未接続
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

import gspread
from gspread.exceptions import SpreadsheetNotFound

from sheets_manager import get_client
from skillplus_student_metrics_sheet_sync import (
    FileLock,
    PROTECTED_EDITOR_EMAILS,
    STATUS_FORMATS,
    apply_status_cell_colors,
    batch_update_with_retry,
    get_all_values_with_retry,
    hex_to_rgb,
    normalize_date,
    normalize_datetime,
    normalize_email,
    normalize_name_key,
    normalize_phone,
    normalize_text,
    repeat_cell_request,
    run_read_with_retry,
    run_write_with_retry,
    set_column_width_request,
    set_row_height_request,
    set_sheet_properties_request,
    style_table,
    worksheet_write_with_retry,
)


SOURCE_SHEET_ID = "1w3TOFPPKQhuXFwMaNMsaU_DAFZDtILkBCUSH9Fc_Bfs"
SOURCE_SPREADSHEET_TITLE = "【スキルプラス】イベント管理シート"
TARGET_SHEET_ID = "1uUqF_dSuKiUAx_6hbAO7stqGHDJch1eUJ_YTusP5lxA"
TARGET_SPREADSHEET_TITLE = "【アドネス株式会社】スキルプラス自動生成データ（加工）"

AUTO_TAB_NAME = "自動生成一覧"
SUMMARY_TAB_NAME = "自動生成サマリー"
SOURCE_MANAGEMENT_TAB_NAME = "データソース管理"
RULE_TAB_NAME = "データ追加ルール"

TAB_SPECS = {
    AUTO_TAB_NAME: (8000, 17),
    SUMMARY_TAB_NAME: (80, 3),
    SOURCE_MANAGEMENT_TAB_NAME: (80, 14),
    RULE_TAB_NAME: (60, 3),
}

BASE_DIR = Path(__file__).resolve().parent
STATE_PATH = BASE_DIR / "data" / "skillplus_autogenerated_metrics_sheet_state.json"
LOCK_PATH = BASE_DIR / "data" / "skillplus_autogenerated_metrics_sheet_sync.lock"

HEADER_BG = {"red": 0.26, "green": 0.52, "blue": 0.96}
HEADER_TEXT = {
    "foregroundColor": {"red": 1, "green": 1, "blue": 1},
    "bold": True,
    "fontSize": 11,
}
TAB_COLORS = {
    AUTO_TAB_NAME: "#1A73E8",
    SUMMARY_TAB_NAME: "#FBBC04",
    SOURCE_MANAGEMENT_TAB_NAME: "#34A853",
    RULE_TAB_NAME: "#9E9E9E",
}
PROTECTION_PREFIX = "スキルプラス自動生成データ（加工）自動生成"

EVENT_TAB_NAME = "📋 イベント予約管理"
ROSTER_TAB_SPECS = {
    "👤 受講生データ_STD": "STD/オールインワン",
    "👤 受講生データ_PRM": "プライム",
    "👤 受講生データ_合宿": "合宿",
}

UNCONNECTED_METRIC_COLUMNS = (
    "連続アクション日数",
    "累計アクション日数",
    "ゴール達成数",
    "最終アクション日",
)

TEST_MARKERS = ("test", "テスト", "てすと", "dummy", "sample", "サンプル", "確認用")
INTERNAL_EXCLUDED_EMAILS = {
    "koa800sea.nifs@gmail.com",
    "sakata28.04@gmail.com",
    "shihokomai.98@gmail.com",
    "nene.m.marching@gmail.com",
    "cheerywisdom008@gmail.com",
    "a@gmail.com",
}
INTERNAL_EXCLUDED_PHONES = {
    "8016649683",
    "9060500388",
    "8015439607",
    "8018141873",
    "8012345678",
}
INTERNAL_EXCLUDED_NAME_MARKERS = ("甲原",)
INTERNAL_EXCLUDED_EXACT_NAMES = (
    "ああ",
    "takamizawa",
    "高見澤@急ぎはﾜﾝｺｰﾙでﾗｲﾝ見ます?",
    "小笠原たつひと",
    "てすとつちや",
)
INTERNAL_EXCLUDED_ADDRESS_MARKERS = ("四谷トーセイビル",)


def normalize_marker_text(value: object) -> str:
    return normalize_text(value).replace("　", " ").strip().lower()


def contains_test_marker(*values: str) -> bool:
    for value in values:
        normalized = normalize_marker_text(value)
        if not normalized:
            continue
        compact = normalized.replace(" ", "")
        if any(marker in compact for marker in TEST_MARKERS):
            return True
    return False


def should_exclude_row(
    email: str,
    phone: str,
    full_name_source: str,
    line_name_source: str,
    address_source: str,
    status_source: str,
) -> bool:
    if contains_test_marker(full_name_source, line_name_source, email, status_source):
        return True
    normalized_name = normalize_marker_text(full_name_source)
    normalized_line_name = normalize_marker_text(line_name_source)
    normalized_address = normalize_marker_text(address_source)
    if email and email in INTERNAL_EXCLUDED_EMAILS:
        return True
    if phone and phone in INTERNAL_EXCLUDED_PHONES:
        return True
    if any(marker in normalized_name or marker in normalized_line_name for marker in INTERNAL_EXCLUDED_NAME_MARKERS):
        return True
    if any(normalized_name == name or normalized_line_name == name for name in INTERNAL_EXCLUDED_EXACT_NAMES):
        return True
    if any(marker in normalized_address for marker in INTERNAL_EXCLUDED_ADDRESS_MARKERS):
        return True
    if normalize_marker_text(status_source) == "スタッフ".lower():
        return True
    populated = sum(
        1
        for value in (
            email,
            phone,
            normalize_text(full_name_source),
            normalize_text(line_name_source),
        )
        if value
    )
    return populated <= 1


def parse_int(value: object) -> int:
    text = normalize_text(value).replace(",", "")
    if not text:
        return 0
    try:
        return int(float(text))
    except ValueError:
        return 0


def header_index(headers: Sequence[str], candidates: Iterable[str]) -> Optional[int]:
    normalized = {normalize_text(candidate).replace(" ", "") for candidate in candidates}
    for index, header in enumerate(headers):
        if normalize_text(header).replace(" ", "") in normalized:
            return index
    return None


def pick_value(row: Sequence[str], index: Optional[int]) -> str:
    if index is None or index >= len(row):
        return ""
    return normalize_text(row[index])


def build_identity(email: str, phone: str, full_name: str, line_name: str, registration_id: str) -> tuple[str, str]:
    if registration_id:
        return f"registration:{registration_id}", "登録ID"
    if email:
        return f"email:{email}", "メールアドレス"
    if phone:
        return f"phone:{phone}", "電話番号"
    full_name_key = normalize_name_key(full_name)
    line_name_key = normalize_name_key(line_name)
    if full_name_key and line_name_key:
        return f"name_line:{full_name_key}:{line_name_key}", "氏名+LINE名"
    if full_name_key:
        return f"name:{full_name_key}", "氏名"
    if line_name_key:
        return f"line:{line_name_key}", "LINE名"
    return "", ""


def get_or_create_target_spreadsheet(gc) -> gspread.Spreadsheet:
    if TARGET_SHEET_ID:
        try:
            spreadsheet = run_read_with_retry(
                "スキルプラス自動生成データ（加工）シートの取得",
                lambda: gc.open_by_key(TARGET_SHEET_ID),
            )
            ensure_spreadsheet_title(spreadsheet)
            return spreadsheet
        except SpreadsheetNotFound:
            pass

    try:
        spreadsheet = run_read_with_retry(
            "スキルプラス自動生成データ（加工）シートの取得",
            lambda: gc.open(TARGET_SPREADSHEET_TITLE),
        )
    except SpreadsheetNotFound:
        spreadsheet = run_write_with_retry(
            "スキルプラス自動生成データ（加工）シートの作成",
            lambda: gc.create(TARGET_SPREADSHEET_TITLE),
        )
    ensure_spreadsheet_title(spreadsheet)
    return spreadsheet


def ensure_spreadsheet_title(spreadsheet) -> None:
    metadata = run_read_with_retry(
        "スキルプラス自動生成データ（加工）シートのメタデータ取得",
        lambda: spreadsheet.fetch_sheet_metadata({"fields": "properties.title"}),
    )
    title = metadata.get("properties", {}).get("title", "")
    if title == TARGET_SPREADSHEET_TITLE:
        return
    batch_update_with_retry(
        spreadsheet,
        {
            "requests": [
                {
                    "updateSpreadsheetProperties": {
                        "properties": {"title": TARGET_SPREADSHEET_TITLE},
                        "fields": "title",
                    }
                }
            ]
        },
        "スキルプラス自動生成データ（加工）のシート名更新",
    )


def ensure_tabs(spreadsheet):
    tabs = {ws.title: ws for ws in spreadsheet.worksheets()}
    for name, (rows, cols) in TAB_SPECS.items():
        if name in tabs:
            ws = tabs[name]
            if ws.row_count != rows or ws.col_count != cols:
                worksheet_write_with_retry(
                    f"{name} タブのサイズ調整",
                    lambda ws=ws, rows=rows, cols=cols: ws.resize(rows=rows, cols=cols),
                )
            continue
        tabs[name] = run_write_with_retry(
            f"{name} タブの作成",
            lambda name=name, rows=rows, cols=cols: spreadsheet.add_worksheet(title=name, rows=rows, cols=cols),
        )

    target_names = set(TAB_SPECS.keys())
    for title, ws in list(tabs.items()):
        if title not in target_names:
            batch_update_with_retry(
                spreadsheet,
                {"requests": [{"deleteSheet": {"sheetId": ws.id}}]},
                f"{title} タブの削除",
            )
            tabs.pop(title, None)

    requests = []
    ordered_names = [AUTO_TAB_NAME, SUMMARY_TAB_NAME, SOURCE_MANAGEMENT_TAB_NAME, RULE_TAB_NAME]
    for idx, name in enumerate(ordered_names):
        ws = tabs[name]
        requests.append(set_sheet_properties_request(ws.id, {"index": idx, "hidden": False}, "index,hidden"))
        requests.append(
            set_sheet_properties_request(
                ws.id,
                {"tabColorStyle": {"rgbColor": hex_to_rgb(TAB_COLORS[name])}},
                "tabColorStyle",
            )
        )
    batch_update_with_retry(spreadsheet, {"requests": requests}, "スキルプラス自動生成データ（加工）のタブ整列")
    return {ws.title: ws for ws in spreadsheet.worksheets()}


def write_rows(spreadsheet, ws, rows: List[List[object]]) -> None:
    max_cols = max((len(row) for row in rows), default=1)
    padded = [list(row) + [""] * max(0, max_cols - len(row)) for row in rows]
    target_rows = max(len(padded), 2)
    if ws.row_count != target_rows or ws.col_count != max_cols:
        worksheet_write_with_retry(
            f"{ws.title} タブのサイズ最適化",
            lambda: ws.resize(rows=target_rows, cols=max_cols),
        )
    worksheet_write_with_retry(f"{ws.title} クリア", lambda: ws.clear())
    worksheet_write_with_retry(
        f"{ws.title} 更新",
        lambda: ws.update(range_name="A1", values=padded, value_input_option="USER_ENTERED"),
    )


def apply_protections(spreadsheet, tabs) -> None:
    protected_names = list(TAB_SPECS.keys())
    target_sheet_ids = {tabs[name].id for name in protected_names}
    metadata = spreadsheet.fetch_sheet_metadata(
        {
            "includeGridData": False,
            "fields": "sheets(properties.sheetId,protectedRanges(protectedRangeId,description,range(sheetId,startRowIndex,endRowIndex,startColumnIndex,endColumnIndex)))",
        }
    )

    requests = []
    existing_sheet_protection = set()
    for sheet in metadata.get("sheets", []):
        sheet_id = sheet.get("properties", {}).get("sheetId")
        for protected_range in sheet.get("protectedRanges", []):
            range_info = protected_range.get("range", {})
            range_sheet_id = range_info.get("sheetId", sheet_id)
            if range_sheet_id in target_sheet_ids:
                has_row = any(key in range_info for key in ("startRowIndex", "endRowIndex"))
                has_col = any(key in range_info for key in ("startColumnIndex", "endColumnIndex"))
                if not has_row and not has_col:
                    existing_sheet_protection.add(range_sheet_id)

    for name in protected_names:
        if tabs[name].id in existing_sheet_protection:
            continue
        requests.append(
            {
                "addProtectedRange": {
                    "protectedRange": {
                        "range": {"sheetId": tabs[name].id},
                        "description": f"{PROTECTION_PREFIX}: {name}",
                        "warningOnly": False,
                        "editors": {"users": PROTECTED_EDITOR_EMAILS},
                    }
                }
            }
        )

    if requests:
        batch_update_with_retry(spreadsheet, {"requests": requests}, "スキルプラス自動生成データ（加工）の保護設定")


def parse_bool(value: object) -> Optional[bool]:
    normalized = normalize_text(value).upper()
    if normalized == "TRUE":
        return True
    if normalized == "FALSE":
        return False
    return None


def build_auto_aggregates(source_ss) -> tuple[list[dict[str, object]], dict[str, object]]:
    students: dict[str, dict[str, object]] = {}
    roster_counts: Counter[str] = Counter()
    excluded_rows = 0

    for tab_name, default_plan in ROSTER_TAB_SPECS.items():
        ws = source_ss.worksheet(tab_name)
        values = get_all_values_with_retry(ws)
        if len(values) < 4:
            continue

        headers = values[2]
        data_rows = values[3:]
        registration_idx = header_index(headers, ("登録ID",))
        line_name_idx = header_index(headers, ("LINE名",))
        full_name_idx = header_index(headers, ("お名前（フルネーム）",))
        phone_idx = header_index(headers, ("電話番号",))
        email_idx = header_index(headers, ("メールアドレス",))
        line_inflow_idx = header_index(headers, ("LINE流入日",))
        admission_idx = header_index(headers, ("入会日",))
        status_idx = header_index(headers, ("ステータス",))
        participation_idx = header_index(headers, ("イベント参加回数",))
        last_event_idx = header_index(headers, ("最終参加日",))
        memo_idx = header_index(headers, ("メモ",))
        plan_idx = header_index(headers, ("プラン名",))

        for row_number, row in enumerate(data_rows, start=4):
            registration_id = pick_value(row, registration_idx)
            email = normalize_email(pick_value(row, email_idx))
            phone = normalize_phone(pick_value(row, phone_idx))
            full_name = pick_value(row, full_name_idx)
            line_name = pick_value(row, line_name_idx)
            status = pick_value(row, status_idx)
            memo = pick_value(row, memo_idx)
            address = ""
            if should_exclude_row(email, phone, full_name, line_name, address, status):
                excluded_rows += 1
                continue

            identity_key, identity_method = build_identity(email, phone, full_name, line_name, registration_id)
            if not identity_key:
                excluded_rows += 1
                continue

            normalized_plan = pick_value(row, plan_idx) or default_plan
            line_inflow_at = normalize_datetime(pick_value(row, line_inflow_idx))
            admission_date = normalize_date(pick_value(row, admission_idx))
            last_event_date = normalize_date(pick_value(row, last_event_idx))
            participation_count = parse_int(pick_value(row, participation_idx))

            student = students.get(identity_key)
            if not student:
                student = {
                    "identity_key": identity_key,
                    "identity_method": identity_method,
                    "plan": normalized_plan,
                    "line_inflow_at": line_inflow_at,
                    "admission_date": admission_date,
                    "status": status,
                    "email": email,
                    "phone": phone,
                    "full_name": full_name,
                    "line_name": line_name,
                    "registration_id": registration_id,
                    "lstep_url": "",
                    "continuous_action_days": "",
                    "cumulative_action_days": "",
                    "goal_achievement_count": "",
                    "event_count": participation_count,
                    "first_event_date": "",
                    "last_event_date": last_event_date,
                    "last_action_date": "",
                    "memo": memo,
                }
                students[identity_key] = student
            else:
                if not student["plan"] and normalized_plan:
                    student["plan"] = normalized_plan
                if line_inflow_at and (not student["line_inflow_at"] or line_inflow_at < student["line_inflow_at"]):
                    student["line_inflow_at"] = line_inflow_at
                if admission_date and (not student["admission_date"] or admission_date < student["admission_date"]):
                    student["admission_date"] = admission_date
                if status and not student["status"]:
                    student["status"] = status
                if email and not student["email"]:
                    student["email"] = email
                if phone and not student["phone"]:
                    student["phone"] = phone
                if full_name and not student["full_name"]:
                    student["full_name"] = full_name
                if line_name and not student["line_name"]:
                    student["line_name"] = line_name
                if registration_id and not student["registration_id"]:
                    student["registration_id"] = registration_id
                student["event_count"] = max(student["event_count"], participation_count)
                if last_event_date and (not student["last_event_date"] or last_event_date > student["last_event_date"]):
                    student["last_event_date"] = last_event_date

            roster_counts[tab_name] += 1

    event_ws = source_ss.worksheet(EVENT_TAB_NAME)
    event_values = get_all_values_with_retry(event_ws)
    event_headers = event_values[0] if event_values else []
    event_rows = event_values[1:] if len(event_values) > 1 else []

    event_date_idx = header_index(event_headers, ("イベント日",))
    friend_id_idx = header_index(event_headers, ("友だちID",))
    line_name_idx = header_index(event_headers, ("LINE名",))
    full_name_idx = header_index(event_headers, ("氏名",))
    url_idx = header_index(event_headers, ("LステップURL", "LステップURL", " LステップURL"))
    attendance_idx = header_index(event_headers, ("出欠",))

    true_event_count = 0
    false_event_count = 0
    for row in event_rows:
        attendance = parse_bool(pick_value(row, attendance_idx))
        if attendance is True:
            true_event_count += 1
        elif attendance is False:
            false_event_count += 1
        if attendance is not True:
            continue

        event_date = normalize_date(pick_value(row, event_date_idx))
        registration_id = pick_value(row, friend_id_idx)
        line_name = pick_value(row, line_name_idx)
        full_name = pick_value(row, full_name_idx)
        lstep_url = pick_value(row, url_idx)

        identity_candidates = []
        if registration_id:
            identity_candidates.append(f"registration:{registration_id}")
        name_line_key = build_identity("", "", full_name, line_name, "")[0]
        if name_line_key:
            identity_candidates.append(name_line_key)
        if full_name:
            full_name_key = normalize_name_key(full_name)
            if full_name_key:
                identity_candidates.append(f"name:{full_name_key}")
        if line_name:
            line_name_key = normalize_name_key(line_name)
            if line_name_key:
                identity_candidates.append(f"line:{line_name_key}")

        matched_student = None
        for candidate in identity_candidates:
            matched_student = students.get(candidate)
            if matched_student:
                break
        if not matched_student:
            continue

        if event_date and (not matched_student["first_event_date"] or event_date < matched_student["first_event_date"]):
            matched_student["first_event_date"] = event_date
        if event_date and (not matched_student["last_event_date"] or event_date > matched_student["last_event_date"]):
            matched_student["last_event_date"] = event_date
        if lstep_url and not matched_student["lstep_url"]:
            matched_student["lstep_url"] = lstep_url

    students_list = sorted(
        students.values(),
        key=lambda item: (
            item["plan"],
            item["line_inflow_at"] or "9999/99/99 99:99:99",
            item["full_name"],
            item["email"],
        ),
    )
    stats = {
        "student_count": len(students_list),
        "source_row_count": sum(roster_counts.values()),
        "excluded_row_count": excluded_rows,
        "event_true_count": true_event_count,
        "event_false_count": false_event_count,
        "roster_counts": dict(roster_counts),
    }
    return students_list, stats


def build_auto_rows(students: list[dict[str, object]]) -> List[List[object]]:
    rows: List[List[object]] = [
        [
            "プラン",
            "LINE流入日",
            "入会日",
            "受講ステータス",
            "メールアドレス",
            "電話番号",
            "お名前",
            "LINE名",
            "連続アクション日数",
            "累計アクション日数",
            "ゴール達成数",
            "イベント参加回数",
            "初回イベント参加日",
            "最終イベント参加日",
            "最終アクション日",
            "登録ID",
            "LステップURL",
        ]
    ]
    for student in students:
        rows.append(
            [
                student["plan"],
                student["line_inflow_at"],
                student["admission_date"],
                student["status"],
                student["email"],
                student["phone"],
                student["full_name"],
                student["line_name"],
                student["continuous_action_days"],
                student["cumulative_action_days"],
                student["goal_achievement_count"],
                student["event_count"],
                student["first_event_date"],
                student["last_event_date"],
                student["last_action_date"],
                student["registration_id"],
                student["lstep_url"],
            ]
        )
    return rows


def build_summary_rows(students: list[dict[str, object]], stats: dict[str, object], checked_at: str) -> List[List[object]]:
    event_participants = sum(1 for student in students if parse_int(student["event_count"]) > 0)
    total_events = sum(parse_int(student["event_count"]) for student in students)
    first_event_dates = [student["first_event_date"] for student in students if student["first_event_date"]]
    last_event_dates = [student["last_event_date"] for student in students if student["last_event_date"]]
    admission_dates = [student["admission_date"] for student in students if student["admission_date"]]
    return [
        ["項目", "値", "補足"],
        ["最終更新日時", checked_at, "自動生成一覧の再生成時刻"],
        ["受講生数", stats["student_count"], "自動生成一覧の行数"],
        ["採用元行数", stats["source_row_count"], "受講生データ_STD / PRM / 合宿の採用行数合計"],
        ["除外行数", stats["excluded_row_count"], "テスト入力・社内スタッフ・極端な疎データを除外"],
        ["イベント参加者数", event_participants, "イベント参加回数が1以上の受講生数"],
        ["累計イベント参加回数", total_events, "受講生タブに記録された参加回数の合計"],
        ["最初の入会日", min(admission_dates) if admission_dates else "", "受講生タブの入会日最小値"],
        ["最初のイベント参加日", min(first_event_dates) if first_event_dates else "", "イベント予約管理の TRUE 行から算出"],
        ["最新イベント参加日", max(last_event_dates) if last_event_dates else "", "受講生タブの最終参加日とイベント予約管理の TRUE 行の最大値"],
        ["連続アクション日数 連携件数", 0, "未接続"],
        ["累計アクション日数 連携件数", 0, "未接続"],
        ["ゴール達成数 連携件数", 0, "未接続"],
        ["最終アクション日 連携件数", 0, "未接続"],
    ]


def build_source_management_rows(source_ss, stats: dict[str, object], checked_at: str) -> List[List[object]]:
    source_url = f"https://docs.google.com/spreadsheets/d/{SOURCE_SHEET_ID}/edit"
    rows: List[List[object]] = [
        [
            "区分",
            "データソース名",
            "優先順位",
            "スプレッドシート",
            "タブ",
            "取得項目",
            "役割",
            "ステータス",
            "最終確認",
            "採用件数",
            "除外件数",
            "補足",
            "対象期間",
            "備考",
        ]
    ]

    for priority, (tab_name, _) in enumerate(ROSTER_TAB_SPECS.items(), start=1):
        rows.append(
            [
                "raw 正本",
                tab_name,
                priority,
                f'=HYPERLINK("{source_url}","【スキルプラス】イベント管理シート")',
                tab_name,
                "登録ID / LINE名 / 氏名 / 電話番号 / メールアドレス / LINE流入日 / 入会日 / ステータス / イベント参加回数 / 最終参加日 / メモ",
                "受講生ごとの自動生成データの正本",
                "正常",
                f"'{checked_at}",
                stats["roster_counts"].get(tab_name, 0),
                0,
                "受講生のプロフィールとイベント参加回数の正本",
                "全期間",
                "",
            ]
        )

    rows.append(
        [
            "raw 正本",
            EVENT_TAB_NAME,
            len(ROSTER_TAB_SPECS) + 1,
            f'=HYPERLINK("{source_url}","【スキルプラス】イベント管理シート")',
            EVENT_TAB_NAME,
            "イベント日 / 友だちID / LINE名 / 氏名 / LステップURL / 出欠",
            "初回イベント参加日と最終イベント参加日の補完",
            "正常",
            f"'{checked_at}",
            stats["event_true_count"],
            stats["event_false_count"],
            "出欠=TRUE だけをイベント参加として採用",
            "全期間",
            "",
        ]
    )

    for metric_name in UNCONNECTED_METRIC_COLUMNS:
        rows.append(
            [
                "未接続指標",
                metric_name,
                "",
                "",
                "",
                metric_name,
                "将来の自己整理欄で使う予定の指標",
                "要確認",
                f"'{checked_at}",
                0,
                0,
                "現時点で信頼できる raw 正本が未接続",
                "全期間",
                "",
            ]
        )
    return rows


def build_rule_rows() -> List[List[object]]:
    return [
        ["項目", "ルール", "補足"],
        ["正本", "イベント管理シートの raw タブだけを読む", "統合シートや他の加工シートは参照しない"],
        ["visible タブ", "自動生成一覧 / 自動生成サマリー / データソース管理 / データ追加ルールだけを持つ", "管理タブを増やしすぎない"],
        ["自動生成一覧", "1行=1受講生", "登録ID -> メール -> 電話 -> 氏名+LINE名 -> 氏名 -> LINE名 の順で重複統合する"],
        ["イベント参加", "受講生タブのイベント参加回数を正本にし、初回イベント参加日はイベント予約管理の出欠=TRUEから補完する", "最終イベント参加日は受講生タブの最終参加日と TRUE 行の最大値を使う"],
        ["未接続指標", "連続アクション日数 / 累計アクション日数 / ゴール達成数 / 最終アクション日は未接続のまま残す", "推測で埋めない"],
        ["除外ルール", "明確なテスト入力、社内スタッフ、会社住所、極端に疎な行は取り込まない", "一文字名だけでは除外しない"],
        ["更新方法", "手入力せず、スクリプト再生成で更新する", "正本は raw シート"],
    ]


def load_run_state() -> Dict[str, object]:
    if not STATE_PATH.exists():
        return {}
    try:
        data = json.loads(STATE_PATH.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def save_run_state(stats: Dict[str, object]) -> None:
    payload = {
        "updated_at": stats["updated_at"],
        "student_count": stats["student_count"],
        "source_row_count": stats["source_row_count"],
        "excluded_row_count": stats["excluded_row_count"],
        "event_true_count": stats["event_true_count"],
        "event_false_count": stats["event_false_count"],
        "spreadsheet_id": stats["spreadsheet_id"],
    }
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2))


def sync_skillplus_autogenerated_metrics_sheet(dry_run: bool = False, gc=None) -> dict:
    with FileLock(LOCK_PATH):
        gc = gc or get_client()
        source_ss = gc.open_by_key(SOURCE_SHEET_ID)
        target = get_or_create_target_spreadsheet(gc)
        tabs = ensure_tabs(target)

        students, source_stats = build_auto_aggregates(source_ss)
        auto_rows = build_auto_rows(students)
        checked_at = datetime.now().strftime("%Y/%m/%d %H:%M")
        summary_rows = build_summary_rows(students, source_stats, checked_at)
        source_rows = build_source_management_rows(source_ss, source_stats, checked_at)
        rule_rows = build_rule_rows()

        stats = {
            "updated_at": checked_at,
            "student_count": source_stats["student_count"],
            "source_row_count": source_stats["source_row_count"],
            "excluded_row_count": source_stats["excluded_row_count"],
            "event_true_count": source_stats["event_true_count"],
            "event_false_count": source_stats["event_false_count"],
            "spreadsheet_id": target.id,
        }

        if dry_run:
            print("【dry-run】受講生数:", stats["student_count"])
            print("【dry-run】採用元行数:", stats["source_row_count"])
            print("【dry-run】除外行数:", stats["excluded_row_count"])
            print("【dry-run】イベント参加TRUE:", stats["event_true_count"])
            print("【dry-run】イベント参加FALSE:", stats["event_false_count"])
            print("【dry-run】sheet_id:", target.id)
            return stats

        write_rows(target, tabs[AUTO_TAB_NAME], auto_rows)
        style_table(
            target,
            tabs[AUTO_TAB_NAME],
            widths=[150, 150, 110, 110, 220, 120, 140, 140, 110, 110, 110, 110, 110, 110, 110, 120, 260],
            center_cols=[0, 2, 3, 8, 9, 10, 11, 12, 13, 14, 15],
            left_cols=[4, 5, 6, 7, 16],
            date_cols=[2, 12, 13, 14],
            header_font_size=10,
        )
        write_rows(target, tabs[SUMMARY_TAB_NAME], summary_rows)
        style_table(
            target,
            tabs[SUMMARY_TAB_NAME],
            widths=[180, 160, 420],
            left_cols=[0, 2],
            center_cols=[1],
        )
        write_rows(target, tabs[SOURCE_MANAGEMENT_TAB_NAME], source_rows)
        style_table(
            target,
            tabs[SOURCE_MANAGEMENT_TAB_NAME],
            widths=[120, 220, 70, 220, 220, 260, 260, 90, 140, 90, 90, 220, 120, 220],
            center_cols=[2, 7, 9, 10, 12],
            left_cols=[0, 1, 3, 4, 5, 6, 11, 13],
        )
        apply_status_cell_colors(target, tabs[SOURCE_MANAGEMENT_TAB_NAME], source_rows, 7)
        write_rows(target, tabs[RULE_TAB_NAME], rule_rows)
        style_table(
            target,
            tabs[RULE_TAB_NAME],
            widths=[160, 520, 340],
            left_cols=[0, 1, 2],
        )

        apply_protections(target, tabs)
        save_run_state(stats)
        print(f"{TARGET_SPREADSHEET_TITLE} を更新しました。")
        print(f"sheet_id={target.id}")
        return stats


def main() -> None:
    parser = argparse.ArgumentParser(description="スキルプラス自動生成データ（加工）を更新する")
    parser.add_argument("--dry-run", action="store_true", help="Sheets へ書き込まず集計だけ行う")
    args = parser.parse_args()
    sync_skillplus_autogenerated_metrics_sheet(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
